# Generated by Django 3.1.4 on 2020-12-11 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('verification_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('isAddressRelated', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='WhoYouUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_path', models.CharField(max_length=100)),
                ('cover_image_path', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoYouApi.whoyouuser')),
            ],
        ),
        migrations.CreateModel(
            name='ContentViewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BinaryField()),
                ('creation_time', models.DateTimeField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoYouApi.content')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoYouApi.whoyouuser')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoYouApi.fieldtype'),
        ),
        migrations.AddField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whoYouApi.whoyouuser'),
        ),
    ]
